console.log("first commit");
console.log("second commit");
console.log("third commit");
console.log("fourth commit");
console.log("fifth commit");
console.log("not present on remote");
console.log("locally ssave");
console.log("feature branch added");
console.log("latest commit");
console.log("latest commit with new line");
console.log("latest commit 2");
console.log("online updatd");
